<a href="https://colab.research.google.com/github/en7HUS1asm/SelfStudy/blob/main/1_4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

1.넘파이

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y

array([3., 6., 9.])

In [5]:
x-y

array([-1., -2., -3.])

In [6]:
x*y

array([ 2.,  8., 18.])

In [7]:
x/y

array([0.5, 0.5, 0.5])

In [8]:
x / 2.0

array([0.5, 1. , 1.5])

In [10]:
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [11]:
A.shape

(2, 2)

In [13]:
A.dtype

dtype('int64')

In [15]:
B = np.array([[3,0], [6,0]])
A+B

array([[4, 2],
       [9, 4]])

In [16]:
A*B

array([[ 3,  0],
       [18,  0]])

In [19]:
X = np.array([[51, 55], [14, 19], [0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [20]:
X[0]

array([51, 55])

In [22]:
X[0][1]

55

In [23]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [25]:
X = X.flatten()
print(X)

[51 55 14 19  0  4]


In [26]:
np.array([0, 2, 4])

array([0, 2, 4])

In [28]:
X[[0,2,4]]

array([51, 14,  0])

In [29]:
X > 15

array([ True,  True, False,  True, False, False])

In [31]:
X[X>15]

array([51, 55, 19])

In [33]:
X[[True, True, False, True, False, False ]]

array([51, 55, 19])